# Generated by Django 3.1.7 on 2021-03-04 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_aprobacionpa_propuestaasamblea_seccion_seccionindividual_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestaasamblea',
            name='usuario_actualizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='asamblea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.asamblea'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.comuna'),
        ),
    ]
