# Generated by Django 3.1.7 on 2021-03-05 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20210303_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='representante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
