version: '3'
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: convergente
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev.docker

    depends_on:
      - db
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py populate_data && python manage.py runserver 0.0.0.0:8000"


volumes:
  postgres_data:
